sudo: required
services:
  - docker

before_install:
#build test images here
  - docker build -t ngzikai/react-test -f ./client/Dockerfile.dev ./client
  #other app builds goes here

script:
 #run all test scripts
  - docker run ngzikai/react-test npm test -- --coverage 
  
after_success:
  - docker build -t ngzikai/multi-client ./client
  - docker build -t ngzikai/multi-worker ./worker
  - docker build -t ngzikai/multi-server ./server
  - docker build -t ngzikai/multi-nginx ./nginx

  #Login to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

  #Take images and push to docker hub
  - docker push ngzikai/multi-client
  - docker push ngzikai/multi-nginx
  - docker push ngzikai/multi-server
  - docker push ngzikai/multi-worker

deploy:
  provider: elasticbeanstalk
  region: ap-southeast-1
  app: multi-docker
  env: MultiDocker-env
  bucket_name: elasticbeanstalk-ap-southeast-1-367158308372
  bucket_path: docker-multi
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: $AWS_SECRET