sudo: required
services:
  - docker

before_install:
#build test images here
  - docker build -t ngzikai/react-test -f ./client/Dockerfile.dev ./client
  #other app builds goes here

script:
 #run all test scripts
  - docker run ngzikai/react-test npm test -- --coverage 
  
after_success:
  - docker build -t ngzikai/multi-client ./client
  - docker build -t ngzikai/multi-worker ./worker
  - docker build -t ngzikai/mult-server ./server
  - docker build -t ngzikai/multi-nginx ./nginx

  #Login to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

  #Take images and push to docker hub
  - docker push ngzikai/multi-client
  - docker push ngzikai/multi-nginx
  - docker push ngzikai/multi-server
  - docker push ngzikai/multi-worker